# I'm not sure what to do on this file
# will read on Jekyll's docs more deeply later

title: thacuber2a03
url: https://thacuber2a03.github.io
highlighter: rouge
markdown: kramdown

# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       layout: "general"
